### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by skudigeym** [ToBinio/useful-brush#10]
Hey, i have a few suggestions:

Mossy blocks drop moss block instead of slimeball,
Brush off brown mooshrooms to get brown mushroom, parrot to feather, turtle to turtle scute, also mobs from another mods like ducks from Ducklings mod...
And a config menu to turn on and off each feature would be nice.

Love your mod!

**Comment by ToBinio** [comment]
just released version [0.2.0](https://modrinth.com/mod/useful-brush/version/0.2.0+mc1.21.0) of the mod 
which includes all but 
> And a config menu to turn on and off each feature would be nice.
