### ISSUE TITLE
When a brush is in the inventory, the block-breaking texture overlay does'nt render.

### ISSUE THREAD

**Issue by D3K4P1T4T0R3** [ToBinio/useful-brush#13]
When a brush is in the inventory (not in the main hand), the overlay texture that shows how broken a block is does'nt show.

Tho, it does show when breaking blocks with the brush, eather in the normal way or when brushing away blocks.

My theory is that its a bug that comes from the "brushing sand/gravel away" mechanic.

**Comment by ToBinio** [comment]
just released a new version [0.2.1](https://modrinth.com/mod/useful-brush/version/0.2.1+mc1.21.0) that should fix this.

thanks a lot for reporting!
