### ISSUE TITLE
Option to disable breaking of non-suspicious blocks

### ISSUE THREAD

**Issue by vico93** [ToBinio/useful-brush#14]
Seems like the mod is causing non-suspicious gravel to just break without dropping anything. Would be possible to disable this, since i rely on gravel from some of my buildings?

**Comment by ToBinio** [comment]
could you elaborate on this a bit more? 
breaking gravel normally (with a shovel e.g.) should (does in the latest version) drop normally.

are you talking about brushing the gravel?

**Comment by vico93** [comment]
> could you elaborate on this a bit more? breaking gravel normally (with a shovel e.g.) should (does in the latest version) drop normally.
> 
> are you talking about brushing the gravel?

exacly. When i brush a suspicious gravel, if i keep brushing after it dropped the item (and become a regular gravel) it gets destroyed instantly without dropping itself.

**Comment by ToBinio** [comment]
just released a new version [0.2.2](https://modrinth.com/mod/useful-brush/changelog) which should fix it.
after brushing sus-sand it now should start slowly breaking the sand. 

Let me know if you are still having any issues! 
and thanks for reporting
