### ISSUE TITLE
brushing coarse dirt

### ISSUE THREAD

**Issue by thimblebird** [ToBinio/useful-brush#15]
with a loottable possibly (just brainstorming here) including things like
- bone
- flint
- clay ball
- string
- feather
- iron nugget
- dyes
- glass bottle
- bowl
- spider eye

just needed bones and thought "i should have a chance to find bones in the ground, right?" and here i am

**Comment by ToBinio** [comment]
Just released a version compatible with [1.20.4](https://modrinth.com/mod/useful-brush/version/0.2.3+mc1.21.4) that contains this.
If you don't want / can't play in 1.20.4 yet, here's a datapack [useful_brush_extra.zip](https://github.com/user-attachments/files/18009059/useful_brush_extra.zip) you can use with all the changes. 

i kept the loottables quite simple, fells free to change them however you want!
if the datapack doesn't work for you let me know!

**Comment by thimblebird** [comment]
> if the datapack doesn't work for you let me know!

it doesn't :(

```
[20:03:14] [Server thread/ERROR]:
Could not find loot_table 'useful_brush_extra:block/dirt'
```

same for sand 

https://mclo.gs/P3JHVzv

**Comment by ToBinio** [comment]
i accidentally ziped the folder instead of its content...
this version should work: [useful_brush_extra.zip](https://github.com/user-attachments/files/18013211/useful_brush_extra.zip)

**Comment by thimblebird** [comment]
> i accidentally ziped the folder instead of its content... this version should work: [useful_brush_extra.zip](https://github.com/user-attachments/files/18013211/useful_brush_extra.zip)

oh yeah sorry, i fixed that myself already but it's still not working (same log basically)

**Comment by ToBinio** [comment]
Oh... you are playing 1.20... mojang changes the some paths in 1.21, thats why it doesnt find the loot_tables
this version should work: [useful_brush_extra.zip](https://github.com/user-attachments/files/18013428/useful_brush_extra.zip)

**Comment by thimblebird** [comment]
> Oh... you are playing 1.20... mojang changes the some paths in 1.21, thats why it doesnt find the loot_tables this version should work: [useful_brush_extra.zip](https://github.com/user-attachments/files/18013428/useful_brush_extra.zip)

still hoping for the create mod to update :( 🙈 sorry for not providing proper information in the first place and thanks, it works!
