### ISSUE TITLE
Slow breaking of sand and gravel

### ISSUE THREAD

**Issue by Cwalpor** [ToBinio/useful-brush#5]
- Brushing diggable blocks or just sand and gravel will eventually break the block at a slower rate than digging.
- Halve the digging speed of digging with hand. 
- Does not drop the block (essentially brushing away the sand/gravel like the sus versions)

- Basically a slow right-click shovel
- Useful for "no left click challenges"
- Useful for going through trail ruins without shoveling the suspicious gravel. Maybe at the cost of digging speed

**Comment by ToBinio** [comment]
implemented in [0.1.1](https://modrinth.com/mod/useful-brush/version/0.1.1+mc1.20.2) should hopefully work

thanks for the suggestion
